### ISSUE TITLE
链接失效了

### ISSUE THREAD

**Issue by heisen-li** [ohos-rs/ohos-rs.github.io#15]
https://ohos.rs/docs/basic/simple-project.html
![image](https://github.com/user-attachments/assets/7ceceb10-3ed3-4aad-8182-adf29998bdce)

**Comment by richerfu** [comment]
@heisen-li  看起来没问题？
<img width="1565" alt="image" src="https://github.com/user-attachments/assets/4966cc3f-4e0a-498e-ad49-af67ab5ee2f7">
