### ISSUE TITLE
How could i set ohos_ndk_home?

### ISSUE THREAD

**Issue by xiaolei123** [ohos-rs/ohos-rs.github.io#3]
Hello, when I was using ohos-rs, I found that I compiled the rs code to generate a dynamic library as described in the document, but the terminal prompted that I could not find ohos_ndk_home. Which directory should I set to be the correct ohos_ndk_home?

**Comment by richerfu** [comment]
> Hello, when I was using ohos-rs, I found that I compiled the rs code to generate a dynamic library as described in the document, but the terminal prompted that I could not find ohos_ndk_home. Which directory should I set to be the correct ohos_ndk_home?

I'm sorry for replying so late. After you have installed deveco studio and sdk, you only need to set `OHOS_NDK_HOME` to the path of a certain version. For example, for API9, its path should be `xx/9`, when executing `ll $OHOS_NDK_HOME`, its result should be as follows:

<img width="647" alt="image" src="https://github.com/ohos-rs/ohos-rs.github.io/assets/32590310/3ab70fcb-1c6b-4b51-9e3b-250b13fcf801">

I will update it on the official website documentation later :)
